default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: nexy_irc_development

test: &test
  <<: *default
  database: nexy_irc_test

production: